name: Scheduled Job

on:
  schedule:
    - cron: '0 * * * *'  # Schedule at every hour of the day PM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      run: echo "$pwd"

#    - name: Set working directory
#      run: cd /weatherInfo/

#    - name: Run script
#      run: ./rx_poc_hourly.sh
