name: Scheduled Job Just for Today

on:
  schedule:
    - cron: '1 1 1 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run script and log output
      run: ./test_print_and_log.sh | tee print_message.log

    - name: Upload Log File
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ./print_message.log
